
language: node_js

node_js:  
  - "10.13.0"
  - node   # <-- add this to your .travis.yml for Node.js projects
branches:
  only:
  - release
jobs:
  include:
    - stage: build
      language: node_js
      before_script:
        - npm install -g gulp-cli
      script: gulp
deploy:
  provider: pages
  local-dir: ./dist
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: release