
language: ruby
cache: bundler
branches:
  only:
  - release
jobs:
  include:
    - stage: build
      language: node_js
      script: gulp
deploy:
  provider: pages
  local-dir: ./dist
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: release